spring:
  profiles: eureka1
server:
  port: 9095
  test: service1 hello
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:9093/eureka/
---
spring:
  profiles: eureka2
server:
  port: 9096
  test: service2 hello
eureka:
  client:
    service-url:
      defaultZone: http://eureka2:9094/eureka/
