spring:
  profiles: eureka1
  application:
    name: cloud-nacos-eureka-server
server:
  port: 9093
eureka:
  datacenter: shanghai
  instance:
    hostname: eureka1
  client:
    service-url:
         defaultZone: http://localhost:9094/eureka/
---
spring:
  profiles: eureka2
  application:
    name: cloud-nacos-eureka-server
server:
  port: 9094
eureka:
  datacenter: shanghai
  instance:
    hostname: eureka2
  client:
    service-url:
         defaultZone: http://localhost:9093/eureka/
